### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by restonslacker** [s-u/emdist#1]
I keep running into a memory error of some sort when I use `emd2d`. I'm assuming that the error should read 'Unable to _allocate_ memory...' but I'm not sure why it's trying to allocate a negative amount. 

``` r
mat_a <- matrix(sample(c(rep(0, 3e+07), floor(runif(501900, 1, 30))), 30501900), 
  nrow = 3575, ncol = 8532)
mat_b <- matrix(sample(c(rep(0, 3e+07), floor(runif(501900, 1, 30))), 30501900), 
  nrow = 3575, ncol = 8532)
emdist::emd2d(mat_a, mat_b)
#> Error in emdr(A, B, dist = dist, ...): Unable to memory (-1620.2 MB) in emdist
```

I'm running R 3.3.2 x64 and emdist 0.3-2 on a machine with 32GB of ram.

**Comment by RdNetwork** [comment]
I am having the exact same issue right now on a large cluster of data. 
R tells me : ` Unable to memory (-918.3 MB) in emdist`

Is there a way to solve this?

**Comment by s-u** [comment]
No, the above example is asking for about 1Tb of memory just for that single allocation, so it's pretty much unfeasible. The way the flow structures work you'll need about _n_ * 27kB of memory (on a 64-bit system), so on a small 32Gb system you can at best deal with about 1e6 entries total. If you see negative sizes, it means long integers are only 32-bit on your system so that puts you in a limit of about 120k entries.

Also note that it won't finish in finite time, either, because the compute time is also quadratic, so the above is really just academic - it's telling you that what you're are trying to do makes no sense. emd is not suitable for large sizes - you may want to look for approximative approaches in the literature.

**Comment by Jeongho-Choi** [comment]
Hi, I have the same issue and am wondering if you have suggestions for alternative approaches. I'm very new to this method, and searching for a list of articles on Google Scholar doesn't seem to help.
